### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by Budincsevity** [NLMartian/SilkCal#3]
Hi! 

Your library looks awesome, and I can't wait to use it in my project.

But when I try to add 'compile 'me.nlmartian.silkcal:silkcal:0.1.0'' to my build.grandle I got Failed to resolve: me.nlmartian.silkcal:silkcal:0.1.0 error.

allprojects {
    repositories {
        jcenter()
    }
}

is in my global build.gradle file.

Thanks for your help!

**Comment by NLMartian** [comment]
The artifact name on jcenter configuration is different from the actual artifact name. It's correct now.
try `compile 'me.nlmartian.silkcal:library:0.1.1'`

**Comment by Budincsevity** [comment]
Thanks, it's working now!
