### ISSUE TITLE
The auto-scrolling position is wrong when adding a toolbar or other view above DayPickerView

### ISSUE THREAD

**Issue by enginebai** [NLMartian/SilkCal#5]
The auto-scrolling position is correct when no any views above `DayPickerView`, but it's wrong when adding some view (such as `Toolbar`).

The following photo shows that the last week of Aug. is disappear of the whole `DayPickerView`:
![132](https://cloud.githubusercontent.com/assets/3387462/10863313/ea78564a-8003-11e5-9477-35b84ca60f1d.png)

**Comment by pingothedoer** [comment]
@NLMartian , @enginebai  Any Solution for this? I am facing the same issue right now...
